#!/bin/bash
# Automatización de servicios
# Modo de uso: copia o mueve este script a /usr/bin o /usr/local/bin y ejecutarlo de esta manera:
# Dar permisos al archivo en /usr/bin -> sudo chmod 777 autoservicios
# autoweb

# Instalar  apache mysql php phpmyadmin coger la base de datos de github e introducira directamente a la base de datos
# Paso 1: Actualizamos el sistema operativo
sudo apt-get update
# Paso 2: Instalar Apache, MySQL, PHP
sudo apt-get install apache2 mysql-client mysql-server php7.0 libapache2-mod-php7.0
# Paso 3: Instalar sofware adicional y necesario
sudo apt-get install graphviz aspell php7.0-pspell php7.0-curl php7.0-gd php7.0-intl php7.0-mysql php7.0-xmlrpc php7.0-ldap php7.0-zip
sudo service apache2 restart
sudo apt-get install git
sudo apt-get install nano
sudo apt-get update
# Paso 4: Instalar PHPMYADMIN y configuracion.
sudo apt-get install phpmyadmin
cd /etc/apache2
sudo chmod 777 apache2.conf
# El echo introduce su contenido en la ultima linea del archivo seleccionado.
echo "include /etc/phpmyadmin/apache.conf" >> apache2.conf
# sudo nano apache2.conf
sudo service apache2 restart
# Paso 5: Crear una base de datos
echo 'Introduce el nombre de la base de datos'
read namebd
mysql -u root -p << MY_QUERY
CREATE DATABASE $namebd;
MY_QUERY
# Paso 6: Descargar de git e instalar BD
echo 'Introduce usuario de Git/Hub:'
read usergit
#davidfc666
echo 'Introduce nombre del repositorio:'
read repogit
#Sqlrubrica
echo 'Introduce nombre del archivo de la base de datos'
read bdgit
#Rubrica
cd /opt
sudo git clone https://github.com/$usergit/$repogit.git
cd
mysql -u root -p $namebd < /opt/$repogit/$bdgit.sql
# Paso 7: Descargar la web e implementarla en var/www/html
cd
sudo chmod -R 777 /var/www/html
cd /var/www/html
echo 'Introduce el nombre de usuario de git'
read namegit
echo 'Introduce el repositorio de git'
read repgit
cd /var/www/html
sudo git clone https://github.com/$namegit/$repgit.git
#unzip $repgit-master.zip
##mkdir reto
#cp -r $repgit-master/ reto
#rmdir $repgit-master